version: '3.8'

services:
  web:
    container_name: hyprsupreme-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - FLASK_ENV=production
      - FLASK_APP=community.web_interface:app
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - hyprsupreme-network

networks:
  hyprsupreme-network:
    driver: bridge

