name: 🐛 Bug Report
description: Report a bug or issue with HyprSupreme-Builder
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        # 🐛 Bug Report
        
        Thanks for taking the time to fill out this bug report! The more details you provide, the faster we can help you.
        
        ---

  - type: checkboxes
    id: checks
    attributes:
      label: ✅ Pre-Check
      description: Please confirm you've completed these steps
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have checked the documentation and troubleshooting guide
          required: true
        - label: I am using the latest version of HyprSupreme-Builder
          required: true

  - type: textarea
    id: description
    attributes:
      label: 🔍 Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug in detail...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots/Logs
      description: If applicable, add screenshots or log files to help explain your problem
      placeholder: |
        Paste screenshots or log content here...
        
        For logs, you can find them in the logs/ directory

  - type: dropdown
    id: os
    attributes:
      label: 🖥️ Operating System
      description: What OS are you running?
      options:
        - Arch Linux
        - EndeavourOS
        - CachyOS
        - Manjaro
        - Garuda Linux
        - Other (please specify)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: 📦 HyprSupreme-Builder Version
      description: What version of HyprSupreme-Builder are you running?
      placeholder: "v2.1.0"
    validations:
      required: true

  - type: input
    id: hyprland-version
    attributes:
      label: 🪟 Hyprland Version
      description: What version of Hyprland are you running?
      placeholder: "hyprland --version"
    validations:
      required: true

  - type: textarea
    id: gpu
    attributes:
      label: 🎮 GPU Information
      description: What GPU are you using?
      placeholder: |
        GPU: NVIDIA RTX 3080
        Driver: nvidia 535.98
        
        Run: lspci | grep VGA
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 📝 Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...

