name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov flake8

    - name: Run Python tests
      run: |
        pytest --cov=tools --cov-report=term-missing --maxfail=5 --disable-warnings -q

    - name: Lint Python code
      run: |
        flake8 tools/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 tools/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test-shell:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install shell testing tools
      run: |
        sudo apt-get update
        sudo apt-get install -y bats shellcheck

    - name: Run shell script linting
      run: |
        find . -name "*.sh" -type f | xargs shellcheck --severity=warning

    - name: Run BATS tests
      run: |
        bats tests/test_*.bats

  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install security tools
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety

    - name: Run security checks
      run: |
        # Check for security issues in Python code
        bandit -r tools/ -f json -o bandit-report.json || true
        
        # Check for known security vulnerabilities in dependencies
        safety check --json --output safety-report.json || true
        
        # Display results
        echo "Security scan completed. Check artifacts for detailed reports."

    - name: Upload security reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json

