name: 📊 Repository Metrics & Badges

on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
    - name: 📈 Generate Repository Metrics
      uses: lowlighter/metrics@latest
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        user: GeneticxCln
        repo: HyprSupreme-Builder
        
        # Base configuration
        base: header, activity, community, repositories, metadata
        base_indepth: yes
        
        # Plugin configurations
        plugin_lines: yes
        plugin_lines_sections: base
        plugin_lines_repositories_limit: 4
        plugin_lines_history_limit: 1
        
        plugin_languages: yes
        plugin_languages_analysis_timeout: 15
        plugin_languages_categories: markup, programming
        plugin_languages_colors: github
        plugin_languages_limit: 8
        plugin_languages_recent_categories: markup, programming
        plugin_languages_recent_days: 14
        plugin_languages_recent_load: 300
        plugin_languages_sections: most-used
        plugin_languages_threshold: 0%
        
        plugin_stargazers: yes
        plugin_stargazers_charts: yes
        plugin_stargazers_charts_type: classic
        
        plugin_contributors: yes
        plugin_contributors_base: contributors
        plugin_contributors_sections: contributors
        plugin_contributors_contributions: yes
        
        plugin_activity: yes
        plugin_activity_limit: 5
        plugin_activity_load: 300
        plugin_activity_days: 14
        plugin_activity_filter: all
        plugin_activity_visibility: all
        plugin_activity_timestamps: yes
        
        # Output
        filename: metrics.svg
        optimize: svg

